// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHsknAbZztlCL3IClOSO_swiZ9E77xcU',
    appId: '1:37285555553:web:475acc918fae310a712920',
    messagingSenderId: '37285555553',
    projectId: 'delicheq-15d66',
    authDomain: 'delicheq-15d66.firebaseapp.com',
    storageBucket: 'delicheq-15d66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUj-_UNhcBjDgBRAMRfLWHVWYO_IgkDuk',
    appId: '1:37285555553:android:a15e4f35b487a43c712920',
    messagingSenderId: '37285555553',
    projectId: 'delicheq-15d66',
    storageBucket: 'delicheq-15d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3zcIzuQ4rSRWL-pb547WITSdm9KCbtcg',
    appId: '1:37285555553:ios:5062766f152c9306712920',
    messagingSenderId: '37285555553',
    projectId: 'delicheq-15d66',
    storageBucket: 'delicheq-15d66.firebasestorage.app',
    iosBundleId: 'com.example.delicheq',
  );
}
